language: minimal
deploy:
  fqdn: jumpcrew-pegau.de
  keep-history: true
  local-dir: public
  target-branch: gh-pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
