name: Update statistics
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  # TODO: use multiple jobs whenever https://github.com/nektos/act/issues/169 is done so act can save artifacts
  statistics:
    name: Update statistics data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DANOPZ_BOT_KEY }}
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install sharp@0
      - name: Query Facebook and write results
        run: node bin/update.facebook.js
        env:
          FB_API_TOKEN: ${{ secrets.FB_API_TOKEN }}
      - name: Query Youtube and write results
        run: node bin/update.youtube.js
        env:
          YT_API_TOKEN: ${{ secrets.YT_API_TOKEN }}
      - run: |
          git config --local user.name "danopz-bot"
          git config --local user.email "bot@copynpaste.de"
          git add public/api
      - run: if [ $(git diff --cached --name-only | wc -l) -ne 0 ]; then
              git commit -m"Automatic API data update";
              git push origin HEAD;
             fi;
